### ISSUE TITLE
Truncating DB does not work for MySQL 5.5 image

### ISSUE THREAD

**Issue by gmta** [docksal/service-db#10]
Running `fin truncate db` does not work in the MySQL 5.5 image since it executes the following:

```
_RUN_NO_CDIR=1 CONTAINER_NAME="db" \
        _exec "echo -e \"$DBCREATE_COMMAND\"| mysql -u${__dump_user} -p${__dump_password} ${__database} "
```

Here, `_exec` always executes a form of `bash -l`. This new login resets the `PATH` environment variable that was set by the parent `mysql:5.5` image.

Correct `PATH`:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/mysql/bin:/usr/local/mysql/scripts
```

Incorrect `PATH` after `bash -l`:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

This causes the `mysql` command to be unavailable and Docksal to fail:

```
Truncating (project) database...
bash: mysql: command not found
```

**Comment by lmakarov** [comment]
Thanks for the report, @GMTA .

I'm not clear why these would be different upstream, but... it is what it is.

I've also been running into some quirks with the new `bash -l` approach used for `cli` and variables set via `ENV` in Dockerfile being dropped. Have not found a solution for that, other than writing suck variables into `~/.profile` instead.

I think, we might just want to limit `bash -l` to `cli` only, unless we find a clever way to preserve/combine the ENV variables set in Dockerfile while using `bash -l`.

**Comment by gmta** [comment]
I've linked a PR to solve the issue in this service image. However, your assertion is correct in that with `bash -l` you always overwrite any `ENV` statement from the Docker image which might not be what you want.

According to you, what would be the expected result from `fin bash`? Would that drop you in an environment as defined by your `/etc/profile`, `~/.bashrc` etc. or should that take into account the environment as set by the Docker image as well?

**Comment by lmakarov** [comment]
@GMTA I would expect Docker image variables to be preserved (as system level variables) and user level variables to be applied on top of the system ones, overwriting existing values if there is an overlap.

**Comment by lmakarov** [comment]
PR merged. Closing.
