### ISSUE TITLE
Increase the redo log size using innodb_log_file_size

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-db#2]
I was getting the following error when trying to import a database dump using `docksal/db:1.1-mysql-5.6`.

```
The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.
```

The issue and the solution is explained on [stackoverflow](https://stackoverflow.com/questions/25277452/how-to-configure-mysql-5-6-longblob-for-large-binary-data/27359753#27359753)

Setting `innodb_log_file_size=128M` solved the problem (the default value is 32MB).

This looks to be only affecting mysql-5.6, but not 5.5, 5.7 and 8.0 images. While all have `innodb_log_file_size=32MB` by default, only 5.6 needs `innodb_log_file_size` bumped up.

**Comment by achekulaev** [comment]
Stumbled upon this today

**Comment by tamnv** [comment]
I have same issue when execute `fin sqli dev.sql`. The size of file is up to 2.8G, I already increase the `innodb_log_file_size` in my.cnf to 512M but it doesn't solve issue. Do I miss other settings?

**Comment by achekulaev** [comment]
@tamnv did you make sure that your setting has applied?

```sql
show variables where Variable_name like "innodb_log_file_size";
```

@lmakarov should we release 1.2 with this change?

**Comment by ilux251** [comment]
You have to restart your mysql service.

**Comment by achekulaev** [comment]
Well yes, of course. I guess documentation states that you need to restart the project.

**Comment by tamnv** [comment]
@achekulaev 
It doesn't apply the settings when we check `show variables where Variable_name like "innodb_log_file_size";` I restart service `fin restart db` but It still doesn't change anything.

**Comment by lmakarov** [comment]
@tamnv you can now switch to the new docksal/db image, which have been just released:

```
docksal/db:1.2-mysql-8.0
docksal/db:1.2-mysql-5.7
docksal/db:1.2-mysql-5.6
docksal/db:1.2-mysql-5.5
```

If you are still experiencing issues with not being able to override mysql settings, then submit a separate issue in the [main project](https://github.com/docksal/docksal/issues/new).

**Comment by tamnv** [comment]
@lmakarov Thank you, It works with `docksal/db:1.2-mysql-5.6`

**Comment by achekulaev** [comment]
@tamnv I see the issue is fixed for you, but on my.cnf

>It doesn't apply the settings when we check 

This ^ means your `my.cnf` was not valid. You can check logs for details `fin logs db`, but most likely you did not include section.
E.g. https://github.com/docksal/drupal7/blob/master/.docksal/etc/mysql/my.cnf
