### ISSUE TITLE
arm64 support for docksal/mysql

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-db#26]
arm64 is not yet supported upstream for the [official MySQL Docker image](https://hub.docker.com/_/mysql).
Upstream issue: https://github.com/docker-library/mysql/issues/318

Other options to get MySQL on arm64:

- Switch to [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags) upstream image
  - Oracle Linux base
  - Has arm64 support only for MySQL 8.0
- Use Ubuntu upstream images and install MySQL from Ubuntu repos (Credit: https://github.com/drud/ddev/issues/3002#issuecomment-945129034)
- Use MariaDB instead of MySQL for the time being

**Comment by kutenai** [comment]
Why was this removed from ToDo?? 
I can't be the only person that is really needing this!! 

Any update on when it might be added?

**Comment by lmakarov** [comment]
https://github.com/docksal/service-mariadb/issues/17 (in scope for the next release) will be a stopgap solution.

Upgrading Docksal's MariaDB images to support ARM can happen pretty soon (within a few days or weeks).

**Comment by kutenai** [comment]
That is great news. I'm actually using the MariaDDB image now, but it seems quite slow.. the mysql image did not work *at all*.. I've technically moved to an external MySQL database since even the mariaDB one is so slow (but functional).

As an "example" - importing out company database took 45minutes on a MySQL 5.7 image, but literally 4 or 5 hours on the MariaDB one. I'll be very interested in testing out the Arm64 version once released.

And - thanks for maintaining these!!!!

**Comment by froboy** [comment]
@lmakarov is there anything to do here apart from waiting for the upstream? It seems... not to be progressing.

~I'm working on a whole bunch of different projects now and it seems a little silly, but I've just added a global setting to override the db image on all my projects and it... works for now:~

~fin config set --global DB_IMAGE='docksal/mariadb:10.3-1.1'~

jk that config only works in the project scope, so it looks like I'll be adding `DB_IMAGE=...` to `docksal-local.env` for all of my projects.

**Comment by froboy** [comment]
Posting if this might help folks. I made a quick alias, so now when I spin up a new project I run `maria` before `fin up`.

```
alias maria="fin config set DB_IMAGE='docksal/mariadb:10.3-1.1' --env=local"
```

**Comment by froboy** [comment]
Sharing DDEV's solution in case it's helpful to someone who's able to pick this up:

https://github.com/drud/ddev/pull/3317

**Comment by lmakarov** [comment]
There is now an Oracle Linux based MySQL 8.0 image available upstream in https://hub.docker.com/_/mysql.

MySQL 5.7 arm64 won't be supported upstream (unless Oracle changes their mind and ships a MySQL 5.7 arm64 package for Debian).

I'm leaning towards dropping support for 5.7 and only supporting 8.0 for docksal/mysql. This will provide a consistent experience between platforms at the cost of retiring the older version prematurely.
