### ISSUE TITLE
MySQL 5.7 compiles successfully with ARM, but does not run properly

### ISSUE THREAD

**Issue by shencangsheng** [docksal/service-db#34]
Mysql Server 5.7 was successfully compiled using Ubuntu16.04 Linux/Arm64. The result file cannot be initialized and run normally in Debian:buster-slim Linux/arm environment, Error : `./bin/mysqld: error while loading shared libraries: libssl.so. 1.0.0: cannot open shared object file: no such file or directory `, the result file cannot be initialized normally in Debian:buster-slim Linux/amd64, Error: `./bin/mysqld no such file or directory`

**Comment by lmakarov** [comment]
MySQL 5.7 in not supported on ARM. Use [docksal/mariadb:10.4](https://github.com/docksal/service-mariadb) as a drop-in replacement.
