### ISSUE TITLE
Implement a healthcheck for MySQL

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-db#6]
Similar to a healthcheck in [docksal/cli](https://github.com/docksal/service-cli/blob/7ed6326fc3d9de8e0006680eaf52af84d0de8caf/7.1/Dockerfile#L358-L359), implement one for MySQL.

Once implemented, `fin` can wait for MySQL to become healthy when bringing up a stack.
This will eliminate the need of `sleep x` in `fin init` scripts when waiting for MySQL to become ready.

**Comment by shelane** [comment]
In our Jenkins process, we had an issue with trying to access our databases because the database was not yet available. This is what we implemented in Jenkins to wait to know when MySQL database was ready:
```
stage("Database Setup") {
            when {
                expression { params.performRelease == false }
            }
            steps {
                sh "docker create -P --name=${DB_CONTAINER_NAME} -v `pwd`:/var/www/html:Z andrewklau/centos-lamp"
                sh "docker start ${DB_CONTAINER_NAME}"

                script {
                    timeout(120) {
                        waitUntil {
                            try {
                                sh "docker exec ${DB_CONTAINER_NAME} mysql --execute 'show databases;'"
                                return true
                            } catch (exception) {
                                return false
                            }
                        }
                    }
                }
            }
        }
```
I'm not sure if this is the kind of thing you're going for with the health check.

**Comment by lmakarov** [comment]
@shelane it has to be a [Docker healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) - a container is expected to be able to figure out and report its own health status. Here's a feature request, which was, sadly, closed as won't fix, but has several examples that can be used anyway: https://github.com/docker-library/mysql/issues/196

**Comment by shelane** [comment]
Fixed in #12.

**Comment by achekulaev** [comment]
@shelane fin does not use it yet.

**Comment by achekulaev** [comment]
Ok I realized that ticket for fin should be in a different repo, so this one is done.

**Comment by shelane** [comment]
Yes, there is a ticket for it in docksal https://github.com/docksal/docksal/issues/554
